models:
  - type: main
    engine: openai
    model: gpt-4.1-mini

rails:
  input:
    flows:
      - self check input

prompts:
  - task: self_check_input
    content: |
      Your task is to check if the user message below complies with the following policy:
      - should not contain harmful or explicit content
      - should not use abusive language


      User message: "{{ user_input }}"

      Question: Should the user message be blocked (Yes or No)?
      Answer:
